Highlight points of complexity
w3c-ccg/did-wg-charter pull request #41
Opened 2019-06-11 21:28 UTC by brentzundel

This PR introduces text which highlights some of the complexity that may come from using DIDs, in addition to the outlined benefits of DIDs, to paint a more complete picture.
This PR addresses issue #36

2019-06-11 21:41 UTC, TallTed commented on index.html
> +Conceptually, the relationship of a DID and a DID method is similar to the
`relationship of a DID`
-> `relationship between a DID`

2019-06-11 21:41 UTC, TallTed commented on index.html
> +relationship of an IETF generic URI and a specific URI scheme (such as the http:
`relationship of an IETF`
-> `relationship between an IETF`

2019-06-11 21:42 UTC, TallTed commented on index.html
> +and https: schemes). It is also similar to the relationship of an IETF generic
`relationship of an IETF`
-> `relationship between an IETF`

2019-06-27 21:28 UTC, ken-ebert approved these changes

2019-06-28 14:54 UTC, msporny commented on index.html
> +      <p>
The more text a W3C Charter has, the more likely one of the 430+ W3C Members are to object to one of the sentences. W3C Charters are meant to be extremely sparse (some would say that the DID WG Charter already has way too much in it). 

The text below is good, we should put it in the DID spec. 

Suggesting that "DIDs ... lead to some complexity" will provide something to pounce on for the organizations that don't want to see this work go anywhere.

2019-06-28 14:54 UTC, msporny requested changes
Let's move this text into the DID spec and not put it in the DID WG Charter.

2019-07-05 01:21 UTC, msporny commented
@brentzundel could you please raise a PR on the DID spec, please? Leaving this PR open until you do that so we don't forget.

2019-07-09 15:58 UTC, jandrieu commented
I'm with @msporny . Similar to #58, these are details suitable to the spec. Not only for the reasons Manu mention, but also because the language is going to change as we advance the work. What goes in the charter should set clear bounds in terms that can suffice for the entire term of the work.

That said, i like the explanation. Perhaps some of the language here could be absorbed into https://github.com/w3c-ccg/did-spec/pull/234

2019-07-15 19:40 UTC, brentzundel commented
I have moved this text to [a PR on the DID Spec](https://github.com/w3c-ccg/did-spec/pull/239)

2019-08-02 21:11 UTC, peacekeeper commented
Since https://github.com/w3c-ccg/did-spec/pull/239 has been merged, I think this PR can now be closed.

2019-08-03 04:13 UTC, brentzundel commented
Closing, as the related PR has been merged into the spec.

2019-08-03 04:13 UTC, closed without merging